# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_pb2 as grpc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class XmlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CsvToXml = channel.unary_unary(
                '/xml.XmlService/CsvToXml',
                request_serializer=grpc__pb2.CsvToXmlRequest.SerializeToString,
                response_deserializer=grpc__pb2.OperationReply.FromString,
                _registered_method=True)
        self.XmlToXsd = channel.unary_unary(
                '/xml.XmlService/XmlToXsd',
                request_serializer=grpc__pb2.XmlToXsdRequest.SerializeToString,
                response_deserializer=grpc__pb2.OperationReply.FromString,
                _registered_method=True)
        self.ValidateXml = channel.unary_unary(
                '/xml.XmlService/ValidateXml',
                request_serializer=grpc__pb2.ValidateXmlRequest.SerializeToString,
                response_deserializer=grpc__pb2.OperationReply.FromString,
                _registered_method=True)
        self.ProcessXml = channel.unary_unary(
                '/xml.XmlService/ProcessXml',
                request_serializer=grpc__pb2.ProcessXmlRequest.SerializeToString,
                response_deserializer=grpc__pb2.OperationReply.FromString,
                _registered_method=True)
        self.GetCollections = channel.unary_unary(
                '/xml.XmlService/GetCollections',
                request_serializer=grpc__pb2.GetCollectionsRequest.SerializeToString,
                response_deserializer=grpc__pb2.GetCollectionsReply.FromString,
                _registered_method=True)


class XmlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CsvToXml(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def XmlToXsd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateXml(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessXml(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XmlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CsvToXml': grpc.unary_unary_rpc_method_handler(
                    servicer.CsvToXml,
                    request_deserializer=grpc__pb2.CsvToXmlRequest.FromString,
                    response_serializer=grpc__pb2.OperationReply.SerializeToString,
            ),
            'XmlToXsd': grpc.unary_unary_rpc_method_handler(
                    servicer.XmlToXsd,
                    request_deserializer=grpc__pb2.XmlToXsdRequest.FromString,
                    response_serializer=grpc__pb2.OperationReply.SerializeToString,
            ),
            'ValidateXml': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateXml,
                    request_deserializer=grpc__pb2.ValidateXmlRequest.FromString,
                    response_serializer=grpc__pb2.OperationReply.SerializeToString,
            ),
            'ProcessXml': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessXml,
                    request_deserializer=grpc__pb2.ProcessXmlRequest.FromString,
                    response_serializer=grpc__pb2.OperationReply.SerializeToString,
            ),
            'GetCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollections,
                    request_deserializer=grpc__pb2.GetCollectionsRequest.FromString,
                    response_serializer=grpc__pb2.GetCollectionsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xml.XmlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xml.XmlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class XmlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CsvToXml(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xml.XmlService/CsvToXml',
            grpc__pb2.CsvToXmlRequest.SerializeToString,
            grpc__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def XmlToXsd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xml.XmlService/XmlToXsd',
            grpc__pb2.XmlToXsdRequest.SerializeToString,
            grpc__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateXml(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xml.XmlService/ValidateXml',
            grpc__pb2.ValidateXmlRequest.SerializeToString,
            grpc__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessXml(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xml.XmlService/ProcessXml',
            grpc__pb2.ProcessXmlRequest.SerializeToString,
            grpc__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xml.XmlService/GetCollections',
            grpc__pb2.GetCollectionsRequest.SerializeToString,
            grpc__pb2.GetCollectionsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
