# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\x12\x03xml\"#\n\x0f\x43svToXmlRequest\x12\x10\n\x08\x63sv_name\x18\x01 \x01(\t\"#\n\x0fXmlToXsdRequest\x12\x10\n\x08xml_name\x18\x01 \x01(\t\"8\n\x12ValidateXmlRequest\x12\x10\n\x08xml_name\x18\x01 \x01(\t\x12\x10\n\x08xsd_name\x18\x02 \x01(\t\"%\n\x11ProcessXmlRequest\x12\x10\n\x08xml_name\x18\x01 \x01(\t\"\x17\n\x15GetCollectionsRequest\"2\n\x0eOperationReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\x13GetCollectionsReply\x12\x13\n\x0b\x63ollections\x18\x01 \x03(\t2\xc4\x02\n\nXmlService\x12\x37\n\x08\x43svToXml\x12\x14.xml.CsvToXmlRequest\x1a\x13.xml.OperationReply\"\x00\x12\x37\n\x08XmlToXsd\x12\x14.xml.XmlToXsdRequest\x1a\x13.xml.OperationReply\"\x00\x12=\n\x0bValidateXml\x12\x17.xml.ValidateXmlRequest\x1a\x13.xml.OperationReply\"\x00\x12;\n\nProcessXml\x12\x16.xml.ProcessXmlRequest\x1a\x13.xml.OperationReply\"\x00\x12H\n\x0eGetCollections\x12\x1a.xml.GetCollectionsRequest\x1a\x18.xml.GetCollectionsReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSVTOXMLREQUEST']._serialized_start=19
  _globals['_CSVTOXMLREQUEST']._serialized_end=54
  _globals['_XMLTOXSDREQUEST']._serialized_start=56
  _globals['_XMLTOXSDREQUEST']._serialized_end=91
  _globals['_VALIDATEXMLREQUEST']._serialized_start=93
  _globals['_VALIDATEXMLREQUEST']._serialized_end=149
  _globals['_PROCESSXMLREQUEST']._serialized_start=151
  _globals['_PROCESSXMLREQUEST']._serialized_end=188
  _globals['_GETCOLLECTIONSREQUEST']._serialized_start=190
  _globals['_GETCOLLECTIONSREQUEST']._serialized_end=213
  _globals['_OPERATIONREPLY']._serialized_start=215
  _globals['_OPERATIONREPLY']._serialized_end=265
  _globals['_GETCOLLECTIONSREPLY']._serialized_start=267
  _globals['_GETCOLLECTIONSREPLY']._serialized_end=309
  _globals['_XMLSERVICE']._serialized_start=312
  _globals['_XMLSERVICE']._serialized_end=636
# @@protoc_insertion_point(module_scope)
